name: 'Netease sign in'

on:
  push:
    branches: 
      - master
  schedule:
    - cron: '0 22 * * *'

jobs:
  netease:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout codes'
      uses: actions/checkout@v2
    - name: '初始化Python'
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'
    - name: '签到'
      env:
        NETEASE_PHONE: ${{ secrets.NETEASE_PHONE }}
        NETEASE_PASSWORD: ${{ secrets.NETEASE_PASSWORD }}
        SENDER_USERNAME: ${{ secrets.SENDER_USERNAME }}
        SENDER_KEY: ${{ secrets.SENDER_KEY }}
        RECEIVERS_NAMES: ${{ secrets.RECEIVERS_NAMES }}
      run: python checkin.py